### PR TITLE
fix: make logos visible in dark mode

### LINKED ISSUE #1193: [BUG] Fix logos in dark model
### What version of eigent are you using?

0.0.82

### System information

Image

### Problem description

Many logos does not look good in dark mode including Eigent's logo

Image

### log

n/a

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by eureka0928**
### Description

Fixes logos that are invisible or hard to see in dark mode:

1. **Eigent logo in Settings page**: The `version-logo.png` (always black) was used instead of the existing theme-aware logo variable. Switched to use `logoSrc` which selects `logo_white.png` in dark mode and `logo_black.png` in light mode.

2. **Provider logos in Models page**: Several provider SVGs use `fill="black"` or `fill="currentColor"` which renders as black in `` tags, making them invisible on dark backgrounds. Applied CSS `filter: invert(1)` in dark mode for affected providers (OpenAI, Anthropic, Moonshot, Ollama, OpenRouter, LM Studio, Z.ai).

### Related Issue

Fixes #1193

### Changes Made

- **`src/pages/Setting.tsx`**: Removed unused `versionLogo` import, renamed `_logoSrc` to `logoSrc`, replaced hardcoded black logo with theme-aware `logoSrc`
- **`src/pages/Setting/Models.tsx`**: Added `DARK_FILL_MODELS` set, `needsInvert()` helper, extracted `appearance` from store, applied `filter: invert(1)` style to affected provider logo `` tags in sidebar, custom model dropdown, and local model dropdown

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

image

### CODE REVIEW

File: src/pages/Setting/Models.tsx [hunk 1]
```diff
@@ -97,9 +97,25 @@ type SidebarTab =
...
 
+// Provider logos that use dark fills (black or currentColor) and need inversion in dark mode
+const DARK_FILL_MODELS = new Set([
+  'openai',
+  'anthropic',
+  'moonshot',
+  'ollama',
+  'openrouter',
+  'lmstudio',
+  'Z.ai',
```
Comment (lightaime) [inline src/pages/Setting/Models.tsx]: Should we change `Z.ai` to `z.ai` to be consistent for the naming conversion? We may also need to change it in other places. Also add `openai-compatible-model`.
```suggestion
  'z.ai',
  'openai-compatible-model',
```

**Comment by Douglasymlai** [comment]
@eureka928 Hi—thanks for the PR. Adding the dark-mode logo by inverting the image is a good approach, and it looks solid.

@lightaime This might be something we’ll want to keep an eye on for future maintenance, but overall it’s a nice UX improvement.

One potential issue though: I’m seeing that the Z AI and LM Studio logos don’t switch to the white version in dark mode. Are you seeing the same on your side?
Screenshot 2026-02-09 at 13 48 18

**Comment by fury0928** [comment]
@Douglasymlai have you run using my branch? can you compare with my screenshot?

**Comment by fury0928** [comment]
@Douglasymlai The code for both Z.ai and LM Studio looks correct — both are in `DARK_FILL_MODELS` and the `needsInvert()` function handles the `local-` prefix stripping for LM Studio. Could you verify you're testing on the latest branch? Also just pushed a fix that normalizes the Z.ai provider ID to lowercase (`'z.ai'`) for consistency and adds `'openai-compatible-model'` to the dark mode inversion set per lightaime's feedback.

File: src/pages/Setting/Models.tsx (hunk 1 above)
Comment (fury0928) [reply src/pages/Setting/Models.tsx]: @lightaime Done — renamed `'Z.ai'` to `'z.ai'` across all four locations (provider ID in `llm.ts`, `DARK_FILL_MODELS`, `getModelImage` map, and backend `PLATFORM_MAPPING` in `chat.py`). Also added `'openai-compatible-model'` to `DARK_FILL_MODELS`.

**Comment by Douglasymlai** [comment]
@eureka928 Yes, I was running on the latest branch. Let me pull the code and test it again.

**Comment by Douglasymlai** [comment]
@eureka928 Yes, it looks great now!

**Comment by fury0928** [comment]
Cool, would you merge?

**Comment by fury0928** [comment]
Hi @Wendong-Fan @bytecii would you merge this PR?
