### PR TITLE
Fix win 0.0.82 prebuilt issue

### LINKED ISSUE #1084: [BUG] Backend Startup Failed due to no Python at uv
### What version of eigent are you using?

0.0.82

### System information

Backend Startup Failed
Error: Backend environment check failed: Error: Command failed: C:\Programs\Eigent\resources\prebuilt\bin\uv.exe run python -c "print('Python OK')" error: Querying Python at `C:\Programs\Eigent\resources\prebuilt\venv\Scripts\python.exe` failed with exit status exit code: 103 [stderr] No Python at '"D:\a\eigent\eigent\resources\prebuilt\cache\uv_python\cpython-3.10.15-windows-x86_64-none\python.exe' Repair failed: Error: Command failed: C:\Programs\Eigent\resources\prebuilt\bin\uv.exe run python -c "print('Python OK')" error: Failed to unzip wheel: babel-2.17.0-py3-none-any.whl Caused by: an upstream reader returned an error: io error occurred: HTTP status client error (403 Forbidden) for url (https://pypi.tuna.tsinghua.edu.cn/packages/b7/b8/3fe70c75fe32afc4bb507f75563d39bc5642255d1d94f1f23604725780bf/babel-2.17.0-py3-none-any.whl) Caused by: io error occurred: HTTP status client error (403 Forbidden) for url (https://pypi.tuna.tsinghua.edu.cn/packages/b7/b8/3fe70c75fe32afc4bb507f75563d39bc5642255d1d94f1f23604725780bf/babel-2.17.0-py3-none-any.whl) Caused by: HTTP status client error (403 Forbidden) for url (https://pypi.tuna.tsinghua.edu.cn/packages/b7/b8/3fe70c75fe32afc4bb507f75563d39bc5642255d1d94f1f23604725780bf/babel-2.17.0-py3-none-any.whl)

### Problem description

I need help

### log

I need help

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 4pmtong**
### Description

This PR fixes Windows prebuilt venv path portability issues and adds macOS x64 / Intel CI build support.

**Summary of changes:**

1. **Prebuilt venv portability and build pipeline**
   - Unifies and tightens prebuilt venv path and install logic for reliable cross-platform use (including Windows).
   - Refines build pipeline scripts and configuration.

2. **Windows path and placeholder fixes**
   - Corrects **Windows path separator** handling in venv portability so build/run no longer fails on Windows due to path format.
   - Fixes **venv placeholder paths** on Windows, resolving the Windows build failure they caused.

3. **CI: macOS x64 and Intel builds**
   - Adds a **macOS x64** build job in `build-view.yml`.
   - Adds **macOS 15 Intel** build so Intel Mac builds and artifacts are available.

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

fix #1084 #943 #998

### CODE REVIEW

**Comment by 4pmtong** [comment]
@Pakchoioioi @Wendong-Fan could you help test the installers? https://github.com/eigent-ai/eigent/actions/runs/21521114829 if works well, we can close #868

File: electron/main/utils/process.ts [hunk 1]
```diff
@@ -151,6 +151,123 @@ export function getCachePath(folder: string): string {
...
+        if (content.includes('{{PREBUILT_VENV_PYTHON}}')) {
+          // Replace placeholder with actual python path
+          const newContent = content.replace(
+            /^#!\{\{PREBUILT_VENV_PYTHON\}\}/m,
+            `#!${pythonExe}`
+          );
+
+          if (newContent !== content) {
+            fs.writeFileSync(filePath, newContent, 'utf-8');
+            fs.chmodSync(filePath, 0o755);
```
Comment (bytecii) [inline electron/main/utils/process.ts]: GPT told me chmod may fail on windows but IDK. Not sure whether we need to only chmod for non windows only.

File: scripts/fix-venv-paths.js [hunk 2]
```diff
@@ -0,0 +1,145 @@
...
+    // Determine if this is Windows or Unix path
+    const isWindowsPath = originalHome.includes('\\') || originalHome.includes('Scripts');
+    const binDir = isWindowsPath ? 'Scripts' : 'bin';
+
+    // Replace with placeholder that will be substituted at runtime
+    // {{PREBUILT_PYTHON_DIR}} will be replaced with the actual path on user's machine
+    // Use appropriate path separator for the platform
+    const pathSep = isWindowsPath ? '\\' : '/';
+    const newHome = `{{PREBUILT_PYTHON_DIR}}${pathSep}${cpythonDir}${pathSep}${binDir}`;
+    content = content.replace(/^home\s*=\s*.+$/m, `home = ${newHome}`);
```
Comment (bytecii) [inline scripts/fix-venv-paths.js:90]: Do we only have one home?

File: scripts/fix-venv-paths.js [hunk 3]
```diff
@@ -0,0 +1,145 @@
...
+    const cpythonMatch = originalHome.match(/(cpython-[\w\.\-]+)/);
+    if (!cpythonMatch) {
+      console.log(`⚠️  Could not extract cpython directory from: ${originalHome}`);
+      return false;
+    }
+
+    const cpythonDir = cpythonMatch[1];
+
+    // Determine if this is Windows or Unix path
+    const isWindowsPath = originalHome.includes('\\') || originalHome.includes('Scripts');
```
Comment (bytecii) [inline scripts/fix-venv-paths.js]: Should we prevent the case that for example
```
home = /opt/vendor/Scripts/cpython-3.10.19-linux-x86_64/bin
```
which is unix but it will detected as windows

Maybe something like
```
const isWindowsPath =
  /^[A-Za-z]:\\/.test(originalHome) || originalHome.startsWith('\\\\') || originalHome.includes('\\');
```

File: scripts/fix-venv-paths.js (hunk 2 above)
Comment (4pmtong) [reply scripts/fix-venv-paths.js:90]: Yes, there should only have one "home" line.

File: electron/main/utils/process.ts (hunk 1 above)
Comment (4pmtong) [reply electron/main/utils/process.ts]: Good catch! `fs.chmodSync()` works on Windows but has different behavior - it can only set/unset the read-only flag, while Unix permissions (0o755) are ignored. However, Node.js won't throw an error; it just silently skips the permission bits on Windows.

File: scripts/fix-venv-paths.js (hunk 3 above)
Comment (4pmtong) [reply scripts/fix-venv-paths.js]: Your suggestion is more robust. I'll push the update and re-test the installers.

File: scripts/fix-symlinks.js [hunk 4]
```diff
@@ -0,0 +1,394 @@
...
+
+    try {
+      // Check if symlink exists
+      let needsFix = false;
+      let currentTarget = null;
+
+      if (
+        fs.existsSync(symlinkPath) ||
+        fs.lstatSync(symlinkPath).isSymbolicLink()
+      ) {
```
Comment (Wendong-Fan) [inline scripts/fix-symlinks.js]: When symlink doesnt exist, lstatSync throws, making the else block at L171 unreachable. Maybe wrap the lstat check in try/catch first?

File: scripts/compile-babel.js [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+const __dirname = path.dirname(fileURLToPath(import.meta.url));
+const projectRoot = path.resolve(__dirname, '..');
+const backendDir = path.join(projectRoot, 'backend');
+const prebuiltVenvDir = path.join(projectRoot, 'resources', 'prebuilt', 'venv');
+const isWindows = process.platform === 'win32';
+
+// Prebuild uses resources/prebuilt/venv; dev may use backend/.venv
+const venvDir = fs.existsSync(prebuiltVenvDir)
+  ? prebuiltVenvDir
+  : path.join(backendDir, '.venv');
```
Comment (Wendong-Fan) [inline scripts/compile-babel.js]: If no venv exists, this fails with ENOENT. Worth adding a quick existence check with a friendly error?

**Review by Wendong-Fan — COMMENTED** [review]
LGTM overall! Just two small things.
